# Generated by Django 6.0.3 on 2026-04-25 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_courseoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseproject',
            name='course',
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('submitter_type', models.CharField(choices=[('student', 'Student'), ('visitor', 'Visitor')], max_length=20)),
                ('overall_rating', models.PositiveSmallIntegerField(help_text='1–5 star rating')),
                ('instructor_rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5 star rating, null for visitors', null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('testimonial_consent', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('drawer', 'Drawer'), ('footer', 'Footer')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_submissions', to='pages.courses')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CourseOffer',
        ),
        migrations.DeleteModel(
            name='CourseProject',
        ),
    ]
